"""hooks -- git hook shim generation, chaining, install/uninstall.

Windows correctness is the whole point. The shims are `sh` scripts executed
by Git-for-Windows' bundled `sh`, which chokes on a bare CR in the exec
line -- shim bytes are therefore rendered with `\n` line endings ONLY and
always written via a *binary* file write (`Path.write_bytes`), never a
text-mode Windows write (which would silently reintroduce CRLF). The
blessed interpreter's ABSOLUTE path is baked into the shim, converted to
Git-for-Windows' `/c/...` form (`win_sh_path`) and double-quoted; a
`command -v py` / `py -3` fallback covers the case where that baked path
has since gone stale -- never invoke a bare `python` (this machine has up
to five different `python`s visible to hook `sh`, including the
WindowsApps store stub).

Exit-code mapping (spec §3, exhaustive -- the shim applies exactly this and
nothing else):
  pre-commit: {2,3} -> 0   (fail-open, always, including engine errors)
  pre-push:   2 -> 0; 1 and 3 pass through and block (an engine that
              couldn't run didn't run gitleaks -- fail-closed)

Hooks inherit the parent process' environment already (git does not
sanitize it), so `ARAMID_ACCEPT_DEGRADED` reaches the engine with no
special forwarding logic needed here.
"""
import stat
import subprocess
import sys
from pathlib import Path

from aramid.models import Gate

MARKER_START = "# >>> aramid managed >>>"
MARKER_END = "# <<< aramid managed <<<"

# The two gates that get a git hook. Gate.ALL is a scan mode (`--all`), not
# a hook.
GATES: tuple[Gate, ...] = (Gate.PRE_COMMIT, Gate.PRE_PUSH)

TRIAGE_HOOK = "post-commit"  # Phase 2a: fail-open triage enqueue (spec section 2)

CHAINED_SUFFIX = ".aramid-chained"


def win_sh_path(p: Path) -> str:
    """`C:\\x\\y` -> `/c/x/y` (Git-for-Windows `sh` form). A path with no
    drive letter (already POSIX-shaped) passes through unchanged, forward
    slashes only."""
    p = Path(p)
    drive = p.drive
    if len(drive) == 2 and drive[1] == ":":
        posix = p.as_posix()
        rest = posix[len(drive):]
        if not rest.startswith("/"):
            rest = "/" + rest
        return f"/{drive[0].lower()}{rest}"
    return p.as_posix()


def _git_config(root: Path, key: str) -> str | None:
    try:
        # noqa justification (S603/S607): "git" is a fixed literal and `key`
        # is always a hardcoded config key passed by this module's own
        # callers (currently only "core.hooksPath") -- never external input.
        # Relying on PATH to resolve "git" matches every other git invoker.
        cp = subprocess.run(["git", "config", key], cwd=str(root),  # noqa: S603,S607
                             capture_output=True, text=True,
                             encoding="utf-8", errors="replace")
    except OSError:
        # git not on PATH (or otherwise unspawnable) -- treat as "unset"
        # rather than propagating a raw exception up through hooks_dir /
        # install / uninstall / probe_interpreter.
        return None
    if cp.returncode == 0 and cp.stdout.strip():
        return cp.stdout.strip()
    return None


def hooks_dir(root: Path) -> Path:
    """Respects `git config core.hooksPath` (husky et al.); else the
    standard `<root>/.git/hooks`. A relative `core.hooksPath` is resolved
    against `root` (git resolves it against the working-tree top level)."""
    configured = _git_config(root, "core.hooksPath")
    if configured:
        p = Path(configured)
        return p.resolve() if p.is_absolute() else (root / p).resolve()
    return root / ".git" / "hooks"


def _exit_case_lines(gate: Gate) -> list[str]:
    if gate is Gate.PRE_COMMIT:
        return ['case "$status" in', "  2|3) exit 0 ;;", '  *) exit "$status" ;;', "esac"]
    return ['case "$status" in', "  2) exit 0 ;;", '  *) exit "$status" ;;', "esac"]


def render_shim(gate: Gate, interpreter: Path) -> bytes:
    """Render the `sh` shim for `gate`. Returns BYTES with `\n` line
    endings ONLY -- never route this through a text-mode write on Windows.

    Always includes a chain-check block that execs a sibling
    `<hook>.aramid-chained` file first, if present -- `install()` is what
    decides whether that sibling exists (rename-on-chain); `render_shim`
    itself is agnostic and this makes re-generation via `install()` safe
    and idempotent (no chaining state is baked into the rendered bytes)."""
    hook = gate.value
    interp_sh = win_sh_path(interpreter)
    lines = [
        "#!/bin/sh",
        MARKER_START,
        f"# aramid managed git hook -- gate: {hook}",
        "# regenerated by `aramid init` / `aramid hooks install` -- do not edit by hand.",
        "",
        'DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)',
        f'CHAINED="$DIR/{hook}{CHAINED_SUFFIX}"',
        'if [ -f "$CHAINED" ]; then',
        '    "$CHAINED" "$@" || exit $?',
        "fi",
        "",
        f'INTERP="{interp_sh}"',
        'if [ -x "$INTERP" ]; then',
        f'    "$INTERP" -m aramid check --gate {hook}',
        "    status=$?",
        "elif command -v py >/dev/null 2>&1; then",
        f"    py -3 -m aramid check --gate {hook}",
        "    status=$?",
        "else",
        '    echo "aramid: no usable python interpreter (tried $INTERP and py -3)" >&2',
        "    status=3",
        "fi",
        "",
        *_exit_case_lines(gate),
        MARKER_END,
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def render_triage_shim(interpreter: Path) -> bytes:
    """Post-commit shim: run triage, swallow EVERYTHING, exit 0. A commit
    can never be blocked or noisy-failed by triage (spec section 6); the
    drain's catch-up sweep recovers anything this shim misses."""
    interp_sh = win_sh_path(interpreter)
    lines = [
        "#!/bin/sh",
        MARKER_START,
        'DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)',
        f'CHAINED="$DIR/{TRIAGE_HOOK}{CHAINED_SUFFIX}"',
        'if [ -f "$CHAINED" ]; then',
        '    "$CHAINED" "$@" || true',
        "fi",
        f'INTERP="{interp_sh}"',
        'if [ -x "$INTERP" ]; then',
        '    "$INTERP" -m aramid triage HEAD >/dev/null 2>&1 || true',
        "elif command -v py >/dev/null 2>&1; then",
        "    py -3 -m aramid triage HEAD >/dev/null 2>&1 || true",
        "fi",
        MARKER_END,
        "exit 0",
        "",
    ]
    return "\n".join(lines).encode()


def _make_executable(path: Path) -> None:
    """`chmod +x` where the platform supports it. Never fatal: NTFS has no
    POSIX permission bits, so this is a best-effort no-op on a bare Windows
    filesystem, but costs nothing and matters on any POSIX-permission
    filesystem the repo might be cloned onto (WSL, a Linux CI runner)."""
    try:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass


def _is_aramid_shim(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        return MARKER_START.encode() in path.read_bytes()
    except OSError:
        return False


def install(root: Path, interpreter: Path) -> None:
    """Install (or idempotently regenerate) the pre-commit/pre-push shims.

    A foreign (non-aramid) hook already occupying a gate's slot is renamed
    to `<hook>.aramid-chained` and the new shim execs it first (see
    `render_shim`'s always-present chain-check block) -- never clobbered.
    Idempotent: marker detection means a second `install()` regenerates
    aramid's own shim in place and never double-chains (an aramid shim
    already at `<hook>` is never itself treated as "foreign")."""
    hdir = hooks_dir(root)
    hdir.mkdir(parents=True, exist_ok=True)

    for gate in GATES:
        hook = gate.value
        shim_path = hdir / hook
        chained_path = hdir / f"{hook}{CHAINED_SUFFIX}"

        if shim_path.exists() and not _is_aramid_shim(shim_path):
            # A real foreign hook (not ours) occupies this slot -- chain it.
            # If a stale .aramid-chained sibling exists too (e.g. a previous
            # uninstall didn't run to completion), the current foreign hook
            # wins as the thing that gets chained.
            if chained_path.exists():
                chained_path.unlink()
            shim_path.replace(chained_path)
            _make_executable(chained_path)

        shim_path.write_bytes(render_shim(gate, interpreter))
        _make_executable(shim_path)

    hook = TRIAGE_HOOK
    shim_path = hdir / hook
    chained_path = hdir / f"{hook}{CHAINED_SUFFIX}"

    if shim_path.exists() and not _is_aramid_shim(shim_path):
        # A real foreign hook (not ours) occupies this slot -- chain it.
        # If a stale .aramid-chained sibling exists too (e.g. a previous
        # uninstall didn't run to completion), the current foreign hook
        # wins as the thing that gets chained.
        if chained_path.exists():
            chained_path.unlink()
        shim_path.replace(chained_path)
        _make_executable(chained_path)

    shim_path.write_bytes(render_triage_shim(interpreter))
    _make_executable(shim_path)


def uninstall(root: Path) -> None:
    """Remove aramid's own shims and restore any `.aramid-chained`
    originals back to their original hook names. A repo that was never
    `install()`-ed is a no-op.

    Guard against losing a hook: the restore step only fires when the
    current `<hook>` file is still aramid's own shim (or absent). If a
    third-party hook manager (e.g. husky's `prepare` script) rewrote
    `<hook>` directly after aramid installed -- so a LIVE foreign hook now
    occupies the slot, with no aramid marker -- restoring the stale
    `.aramid-chained` original over it would silently destroy that live
    hook. In that case the live foreign hook is left untouched and the
    now-orphaned `.aramid-chained` backup is discarded instead, with a
    printed notice."""
    hdir = hooks_dir(root)
    if not hdir.exists():
        return

    for hook in [g.value for g in GATES] + [TRIAGE_HOOK]:
        shim_path = hdir / hook
        chained_path = hdir / f"{hook}{CHAINED_SUFFIX}"

        was_ours = _is_aramid_shim(shim_path)
        if was_ours:
            shim_path.unlink()

        if not chained_path.exists():
            continue

        if was_ours or not shim_path.exists():
            chained_path.replace(shim_path)
            _make_executable(shim_path)
        else:
            # shim_path exists and is NOT aramid's shim: a foreign hook
            # manager replaced it after install. Never overwrite a live
            # foreign hook -- discard the orphaned chained backup instead.
            chained_path.unlink()
            print(f"aramid: uninstall: {hook}: a foreign hook replaced aramid's "
                  f"shim after install -- left the live foreign hook in place "
                  f"and discarded the stale chained backup.", file=sys.stderr)
